version: "2"
services:
  nginx:
    image: kitunda/the-kulture-web:1.0.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/
    restart: on-failure
  api:
    image: kitunda/the-kulture-api:1.0.0
    restart: on-failure
    environment:
      - TZ=Africa/Nairobi
      - APP_MEDIA_STORAGE_DIRECTORY=/uploads
      - APP_ROUTING_ORS_API_KEY=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjliM2Q2NTVkZDNiNTQxYjM4N2EyMzEzMmMwMTcyM2M1IiwiaCI6Im11cm11cjY0In0=
      - SERVER_SERVLET_SESSION_COOKIE_SAME_SITE=none
      - SERVER_SERVLET_SESSION_COOKIE_SECURE=true
    ports:
      - '8080:8080'
    volumes:
      - ./uploads:/uploads
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
